# Copyright (2024) Tsinghua University, Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model:
  use_extracted_feature: True # Set True to use pre-extracted whisper encoder representations (TLTR module inputs) 
  
  use_whisper: True
  use_tltr: True 
  tltr_embed_dim : 1280
  tltr_downsampling_rate : 40 # 1000 => 25
  whisper_config_d_model: 1280

  llama_path: "./checkpoints/vicuna-7b-v1.5" # vicuna-7b-v1.5 ckpt here
  whisper_path: "./checkpoints/whisper-large-v3" # whisper-large-v3 ckpt here

  qformer_ckpt: ""
  tltr_ckpt: ""
  text_plora_ckpt: ""
  emotion_plora_ckpt: ""

  freeze_whisper: True
  freeze_lora: False

  # Q-Former
  use_speech_Qformer: True
  freeze_speech_QFormer: False
  num_speech_query_token: 25

  speech_llama_proj_model: ""
  freeze_speech_llama_proj: False

  # LoRA
  lora: True
  use_plora: True

  use_text_plora: True
  text_plora_rank : 8
  text_plora_alpha : 32
  text_plora_dropout : 0.1
  text_plora_target_modules : "q_proj,v_proj"

  use_emotion_plora: True
  emotion_plora_rank : 8
  emotion_plora_alpha : 32
  emotion_plora_dropout : 0.1
  emotion_plora_target_modules : "q_proj,v_proj"

  multi_prompt: True
  dialogue_prompt: False
  use_emotion_label: False
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "./prompts/stage01_1_train_prompt.json"
  test_prompt_path: "./prompts/stage01_1_test_prompt.json"
  max_txt_len: 300
  end_sym: "</s>"

datasets:
  train_ann_path: "./data/stage01_1_train.json"
  valid_ann_path: "./data/stage01_1_valid.json"
  test_ann_path: "./data/stage01_1_test.json"

  whisper_path: "./checkpoints/whisper-large-v3" # whisper-large-v3 ckpt here

run:
  # log & settings
  seed: 42
  output_dir: "./logs/jelly_llm"
  evaluate: False # if True, only evaluate model on test data

  log_freq: 5
  epoch_based: False
  iters_per_epoch: 3000 #3000
  accum_grad_iters: 1
  batch_size_train: 8 #8
  batch_size_eval: 8 #8
  num_workers: 8

  device: "cuda"
  use_distributed: True
  amp: True
  world_size: 1
  dist_url: "env://"

  # optimizer & scheduler
  optims:
    max_epoch: 30
    warmup_steps: 3000
    warmup_start_lr: 1e-6
    init_lr: 3e-5
    min_lr: 1e-5
    weight_decay: 0.05
    beta2: 0.999